/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion.almacen;

import java.awt.Color;
import java.nio.file.Path;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author mario
 */
public class Formulario_Cliente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Formulario_Cliente.class.getName());
    
    private JFrame padre;
    
//Variables booleanas para comprobar todo
    boolean Codigocomprobado = false;
    boolean nifComprobado = false;
    boolean nif2Comprobado = false;
    boolean nombreComprobado = false;
    boolean apellidosComprobado = false;
    boolean domicilioComprobado = false;
    boolean cpComprobado = false;
    boolean localidadComprobado = false;
    boolean telefonoComprobado = false;
    boolean movilComprobado = false;
    boolean faxComprobado = false;
    boolean mailComprobado = false;
    
    /**
     * Creates new form Formulario
     */
    public Formulario_Cliente(JFrame padre) {
        initComponents();
        this.padre = padre;
    }
    
    public Formulario_Cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codigo = new javax.swing.JLabel();
        nif = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        apellidos = new javax.swing.JLabel();
        domicilio = new javax.swing.JLabel();
        cp = new javax.swing.JLabel();
        localidad = new javax.swing.JLabel();
        telefono = new javax.swing.JLabel();
        movil = new javax.swing.JLabel();
        fax = new javax.swing.JLabel();
        mail = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        textoCodigo = new javax.swing.JTextField();
        textoNif = new javax.swing.JTextField();
        textoNif2 = new javax.swing.JTextField();
        textoNombre = new javax.swing.JTextField();
        textoApellidos = new javax.swing.JTextField();
        textoDomicilio = new javax.swing.JTextField();
        textoCp = new javax.swing.JTextField();
        textoLocalidad = new javax.swing.JTextField();
        textoTelefono = new javax.swing.JTextField();
        textoMovil = new javax.swing.JTextField();
        textoFax = new javax.swing.JTextField();
        textoMail = new javax.swing.JTextField();
        textoTotal = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JButton();
        botonRechazar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        codigo.setText("Código");

        nif.setText("N.I.F");

        nombre.setText("Nombre");

        apellidos.setText("Apellidos");

        domicilio.setText("Domicilio");

        cp.setText("C.P");

        localidad.setText("Localidad");

        telefono.setText("Telefono");

        movil.setText("Movil");

        fax.setText("Fax");

        mail.setText("e-mail");

        total.setText("Total");

        textoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoCodigoActionPerformed(evt);
            }
        });

        textoNif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNifActionPerformed(evt);
            }
        });

        textoNif2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNif2ActionPerformed(evt);
            }
        });

        textoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNombreActionPerformed(evt);
            }
        });

        textoApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoApellidosActionPerformed(evt);
            }
        });

        textoDomicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoDomicilioActionPerformed(evt);
            }
        });

        textoCp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoCpActionPerformed(evt);
            }
        });

        textoLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoLocalidadActionPerformed(evt);
            }
        });

        textoTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoTelefonoActionPerformed(evt);
            }
        });

        textoMovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoMovilActionPerformed(evt);
            }
        });

        textoFax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoFaxActionPerformed(evt);
            }
        });

        textoMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoMailActionPerformed(evt);
            }
        });

        textoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoTotalActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonRechazar.setText("Cancelar");
        botonRechazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRechazarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(domicilio)
                                .addGap(48, 48, 48))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(codigo)
                                    .addComponent(textoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nif)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textoNif, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoNif2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre)))
                    .addComponent(textoCp, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telefono)
                            .addComponent(textoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(movil)
                            .addComponent(textoMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fax)
                            .addComponent(textoFax, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cp)
                        .addGap(119, 119, 119)
                        .addComponent(localidad))
                    .addComponent(apellidos)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(botonAceptar)
                            .addGap(23, 23, 23)
                            .addComponent(botonRechazar))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(textoMail, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(61, 61, 61))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(mail)
                                    .addGap(271, 271, 271)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(total)
                                .addComponent(textoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(140, 140, 140)
                            .addComponent(textoLocalidad, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                        .addComponent(textoDomicilio)
                        .addComponent(textoApellidos)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo)
                    .addComponent(nif)
                    .addComponent(nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoNif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoNif2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(apellidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(domicilio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cp)
                    .addComponent(localidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoCp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefono)
                    .addComponent(movil)
                    .addComponent(fax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoMovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mail)
                    .addComponent(total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar)
                    .addComponent(botonRechazar))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoCodigoActionPerformed
        // TODO add your handling code here:
        //5 numeros
        
        String texto = textoCodigo.getText();
        if (!texto.matches("[0-9]{5}")){
            textoCodigo.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Debe ser una cadena de 5 dígitos","Error",JOptionPane.ERROR_MESSAGE);
            textoCodigo.setText("");
            textoCodigo.setBackground(Color.white);
            textoCodigo.requestFocus();
        } else {
            textoCodigo.addActionListener(e -> textoNif.requestFocus());
            Codigocomprobado = true;
        }
                
    }//GEN-LAST:event_textoCodigoActionPerformed
    //Todo: Generar automáticamente con fórmula matemática
    private void textoNifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNifActionPerformed
        // TODO add your handling code here:
        String texto = textoNif.getText();
        if (!texto.matches("[0-9]{8}")) {
            textoNif.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Debe ser una cadena de 8 dígitos","Error",JOptionPane.ERROR_MESSAGE);
            textoNif.setText("");
            textoNif.setBackground(Color.white);
            textoNif.requestFocus();
        } else {
            textoNif.addActionListener(e -> textoNif2.requestFocus());
            nifComprobado = true;
        }
    }//GEN-LAST:event_textoNifActionPerformed

    private void textoNif2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNif2ActionPerformed
        // TODO add your handling code here:
        String texto = textoNif2.getText();
        if (!texto.matches("[A-Z]")) {
            textoNif2.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Debe ser una letra mayúscula","Error",JOptionPane.ERROR_MESSAGE);
            textoNif2.setText("");
            textoNif2.setBackground(Color.white);
            textoNif2.requestFocus();
        } else{
            textoNif2.addActionListener(e -> textoNombre.requestFocus());
            nif2Comprobado = true;
        }
        
    }//GEN-LAST:event_textoNif2ActionPerformed

    private void textoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNombreActionPerformed
        // TODO add your handling code here:
        String texto = textoNombre.getText();
        if (texto.isEmpty()) {
            textoNombre.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "No puedes dejar este campo vacío","Error",JOptionPane.ERROR_MESSAGE);
            textoNombre.setText("");
            textoNombre.setBackground(Color.white);
            textoNombre.requestFocus();
        } else if (!texto.matches("^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s]+$")){
            textoNombre.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "El nombre debe contener solo letras","Error",JOptionPane.ERROR_MESSAGE);
            textoNombre.setText("");
            textoNombre.setBackground(Color.white);
            textoNombre.requestFocus();
        } else{
            textoNombre.addActionListener(e -> textoApellidos.requestFocus());
            nombreComprobado = true;
        }
    }//GEN-LAST:event_textoNombreActionPerformed

    private void textoApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoApellidosActionPerformed
        // TODO add your handling code here:
        String texto = textoApellidos.getText();
        if (texto.isEmpty()) {
            textoApellidos.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "No puedes dejar este campo vacío","Error",JOptionPane.ERROR_MESSAGE);
            textoApellidos.setText("");
            textoApellidos.setBackground(Color.white);
            textoApellidos.requestFocus();
        } else if (!texto.matches("^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s]+$")){
            textoApellidos.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Los apellidos deben contener solo letras","Error",JOptionPane.ERROR_MESSAGE);
            textoApellidos.setText("");
            textoApellidos.setBackground(Color.white);
            textoApellidos.requestFocus();
        } else{
            textoApellidos.addActionListener(e -> textoDomicilio.requestFocus());
            apellidosComprobado = true;
        }
    }//GEN-LAST:event_textoApellidosActionPerformed

    private void textoDomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoDomicilioActionPerformed
        // TODO add your handling code here:
        String texto = textoDomicilio.getText();
        if (texto.isEmpty()) {
            textoDomicilio.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "No puedes dejar este campo vacío","Error",JOptionPane.ERROR_MESSAGE);
            textoDomicilio.setText("");
            textoDomicilio.setBackground(Color.white);
            textoDomicilio.requestFocus();
        } else{
            textoDomicilio.addActionListener(e -> textoCp.requestFocus());
            domicilioComprobado = true;
        }
    }//GEN-LAST:event_textoDomicilioActionPerformed

    private void textoCpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoCpActionPerformed
        // TODO add your handling code here:
        String cp = textoCp.getText();
        if (!cp.matches("[0-9]{5}")) {
            textoCp.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Debe ser una cadena de 5 dígitos","Error",JOptionPane.ERROR_MESSAGE);
            textoCp.setText("");
            textoCp.setBackground(Color.white);
            textoCp.requestFocus();
        } else{
            textoCp.addActionListener(e -> textoLocalidad.requestFocus());
            cpComprobado = true;
        }
    }//GEN-LAST:event_textoCpActionPerformed

    private void textoLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoLocalidadActionPerformed
        // TODO add your handling code here:
        String texto = textoLocalidad.getText();
        if (texto.isEmpty()) {
            textoLocalidad.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "No puedes dejar este campo vacío","Error",JOptionPane.ERROR_MESSAGE);
            textoLocalidad.setText("");
            textoLocalidad.setBackground(Color.white);
            textoLocalidad.requestFocus();
        } else if (!texto.matches("^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s]+$")){
            textoLocalidad.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "La localidad debe contener solo letras","Error",JOptionPane.ERROR_MESSAGE);
            textoLocalidad.setText("");
            textoLocalidad.setBackground(Color.white);
            textoLocalidad.requestFocus();
        } else{
            textoLocalidad.addActionListener(e -> textoTelefono.requestFocus());
            localidadComprobado = true;
        }
    }//GEN-LAST:event_textoLocalidadActionPerformed

    private void textoTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoTelefonoActionPerformed
        // TODO add your handling code here:
        String texto = textoTelefono.getText();
        if (!texto.matches("[0-9]{9}")) {
            textoTelefono.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Debe ser una cadena de 9 dígitos","Error",JOptionPane.ERROR_MESSAGE);
            textoTelefono.setText("");
            textoTelefono.setBackground(Color.white);
            textoTelefono.requestFocus();
        } else{
            textoTelefono.addActionListener(e -> textoMovil.requestFocus());
            telefonoComprobado = true;
        }
    }//GEN-LAST:event_textoTelefonoActionPerformed

    private void textoMovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoMovilActionPerformed
        // TODO add your handling code here:
        String texto = textoMovil.getText();
        if (!texto.matches("[0-9]{9}")) {
            textoMovil.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Debe ser una cadena de 9 dígitos","Error",JOptionPane.ERROR_MESSAGE);
            textoMovil.setText("");
            textoMovil.setBackground(Color.white);
            textoMovil.requestFocus();
        } else{
            textoMovil.addActionListener(e -> textoFax.requestFocus());
            movilComprobado = true;
        }
    }//GEN-LAST:event_textoMovilActionPerformed

    private void textoFaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoFaxActionPerformed
        // TODO add your handling code here:
        String texto = textoFax.getText();
        if (!texto.matches("[0-9]{9}")) {
            textoFax.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Debe ser una cadena de 9 dígitos","Error",JOptionPane.ERROR_MESSAGE);
            textoFax.setText("");
            textoFax.setBackground(Color.white);
            textoFax.requestFocus();
        } else{
            textoFax.addActionListener(e -> textoMail.requestFocus());
            faxComprobado = true;
        }
    }//GEN-LAST:event_textoFaxActionPerformed

    private void textoMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoMailActionPerformed
        // TODO add your handling code here:
        String texto = textoMail.getText();
        if (texto.isEmpty()) {
            textoMail.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "No puedes dejar este campo vacío","Error",JOptionPane.ERROR_MESSAGE);
            textoMail.setText("");
            textoMail.setBackground(Color.white);
            textoMail.requestFocus();
        } else{
            textoMail.addActionListener(e -> textoTotal.requestFocus());
            mailComprobado = true;
        }
    }//GEN-LAST:event_textoMailActionPerformed

    private void textoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoTotalActionPerformed
        // TODO add your handling code here:
        //Valor 0
        textoTotal.setText("0");
        textoTotal.addActionListener(e -> botonAceptar.requestFocus());
    }//GEN-LAST:event_textoTotalActionPerformed

    private void botonRechazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRechazarActionPerformed
        // TODO add your handling code here:
        textoCodigo.setText("");
        textoNif.setText("");
        textoNif2.setText("");
        textoNombre.setText("");
        textoApellidos.setText("");
        textoDomicilio.setText("");
        textoCp.setText("");
        textoLocalidad.setText("");
        textoTelefono.setText("");
        textoMovil.setText("");
        textoFax.setText("");
        textoMail.setText("");
        textoTotal.setText("");
    }//GEN-LAST:event_botonRechazarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        
        //Icono personalizado
        Path p = Path.of("src", "main", "java", "formulario", "IconoVerde.jpg");
        ImageIcon imagen = new ImageIcon(p.toString());
        imagen = new ImageIcon(imagen.getImage().getScaledInstance(70, 70, 0));
        
// Abrir ventana si todo ha ido bien
        if (Codigocomprobado && 
                nifComprobado && 
                nif2Comprobado && 
                nombreComprobado && 
                apellidosComprobado && 
                domicilioComprobado && 
                cpComprobado && 
                localidadComprobado &&
                telefonoComprobado &&
                movilComprobado &&
                faxComprobado && 
                mailComprobado) {
            JOptionPane.showMessageDialog(null, 
                    "Todos los campos estan bien", 
                    "¡Enhorabuena!",
                    JOptionPane.INFORMATION_MESSAGE,
                    imagen);
        } else{
            JOptionPane.showMessageDialog(null, 
                    "Uno o más campos están mal, vuelve a escribirlos y cuando acabes pulsa enter para comprobar", 
                    "ERROR",
                    JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_botonAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Formulario_Cliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidos;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonRechazar;
    private javax.swing.JLabel codigo;
    private javax.swing.JLabel cp;
    private javax.swing.JLabel domicilio;
    private javax.swing.JLabel fax;
    private javax.swing.JLabel localidad;
    private javax.swing.JLabel mail;
    private javax.swing.JLabel movil;
    private javax.swing.JLabel nif;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel telefono;
    private javax.swing.JTextField textoApellidos;
    private javax.swing.JTextField textoCodigo;
    private javax.swing.JTextField textoCp;
    private javax.swing.JTextField textoDomicilio;
    private javax.swing.JTextField textoFax;
    private javax.swing.JTextField textoLocalidad;
    private javax.swing.JTextField textoMail;
    private javax.swing.JTextField textoMovil;
    private javax.swing.JTextField textoNif;
    private javax.swing.JTextField textoNif2;
    private javax.swing.JTextField textoNombre;
    private javax.swing.JTextField textoTelefono;
    private javax.swing.JTextField textoTotal;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
